TESTS = \
    sc2sc_native \
    sc2sc_uvmc

#
# //-----------------------------------------------------------//
# //   Copyright 2021 Siemens EDA                              //
# //                                                           //
# //   Licensed under the Apache License, Version 2.0 (the     //
# //   "License"); you may not use this file except in         //
# //   compliance with the License.  You may obtain a copy of  //
# //   the License at                                          //
# //                                                           //
# //       http://www.apache.org/licenses/LICENSE-2.0          //
# //                                                           //
# //   Unless required by applicable law or agreed to in       //
# //   writing, software distributed under the License is      //
# //   distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  //
# //   CONDITIONS OF ANY KIND, either express or implied.      //
# //   See the License for the specific language governing     //
# //   permissions and limitations under the License.          //
# //-----------------------------------------------------------//

UVMC_HOME ?= ../..
VSIM_EXTRA ?=
MAKE_CMD = $(MAKE) -f Makefile.questa

help:
	@echo " -----------------------------------------------------------------";
	@echo "|                  UVMC EXAMPLES - CONNECTIONS                    |";
	@echo " -----------------------------------------------------------------";
	@echo "|                                                                 |";
	@echo "| Usage:                                                          |";
	@echo "|                                                                 |";
	@echo "|   make [UVMC_HOME=path] <example>               |";
	@echo "|                                                                 |";
	@echo "| where <example> is one or more of:                              |";
	@echo "|                                                                 |";
	@echo "|   sc2sc_native : SC producer --> SC consumer                    |";
	@echo "|                  Connection is made via standard IEEE TLM in SC |";
	@echo "|                                                                 |";
	@echo "|   sc2sc_uvmc   : SC producer --> SC consumer                    |";
	@echo "|                  Connection is made via UVMC. Semantically      |";
	@echo "|                  equivalent to sc2sc_native                     |";
	@echo "|                                                                 |";
	@echo "| UVMC_HOME specifies the location of the source                  |";
	@echo "| headers and macro definitions needed by the examples. You must  |";
	@echo "| specify their locations via UVM_HOME and UVMC_HOME environment  |";
	@echo "| variables or make command line options. Command line options    |";
	@echo "| override any envrionment variable settings.                     |";
	@echo "|                                                                 |";
	@echo "| The UVMC "standalone OSCI" libraries must be compiled prior to  |";
	@echo "| running                                                         |";
	@echo "| any example. If the libraries are not at their default location |";
	@echo "| (UVMC_HOME/lib) then you must specify their location via the    |";
	@echo "| UVMC_LIB environment variables or make command                  |";
	@echo "| line options. Make command line options take precedence.        |";
	@echo "|                                                                 |";
	@echo "| Other options:                                                  |";
	@echo "|                                                                 |";
	@echo "|   all   : Run all examples                                      |";
	@echo "|   clean : Remove simulation files and directories               |";
	@echo "|   help  : Print this help information                           |";
	@echo "|                                                                 |";
	@echo " -----------------------------------------------------------------";

include $(UVMC_HOME)/examples/common/Makefile.questa

CHECK_TESTS=$(TESTS:%=check.%)

all: sim check clean

OPT = -O3
CFLAGS = \
	$(OPT) -DSC_INCLUDE_DYNAMIC_PROCESSES -fPIC -Wall
INCL = \
    -I$(UVMC_HOME)/src/connect/sc -I$(QUESTA_HOME)/include \
    -I$(SYSTEMC)/include -I$(SYSTEMC_TLM_HOME) -I$(SYSTEMC_TLM_HOME)/tlm_utils

#----------------------------------------------------
# UVM and UVMC (XL-UVM-Connect) libraries are needed to support
# XLerated and trans-language TLM conduits.
UVMC_LIB_OBJ = $(UVMC_HOME)/lib/osci/$(UVMC_BUILD_PLATFORM)
UVMC_LIB_SO = \
    $(UVMC_LIB_OBJ)/uvmc.so \
    $(UVMC_LIB_OBJ)/uvmc_stubs.so

LDFLAGS = \
    -Wl,-E -L$(SYSTEMC)/$(SYSC_LIB) -lsystemc -ldl -lm -lpthread

sim: $(TESTS)
check: $(CHECK_TESTS)

sc2sc_native:
	$(CXX) $(CFLAGS) $(INCL) -Icommon $@.cpp -o $@ $(LDFLAGS)
	./$@ 2>&1 | tee check.$@.log

sc2sc_uvmc:
	$(CXX) $(CFLAGS) $(INCL) -Icommon $@.cpp -o $@ $(UVMC_LIB_SO) $(LDFLAGS)
	./$@ 2>&1 | tee check.$@.log

$(CHECK_TESTS):
	cat $@.log |  \
		perl gold/check.pl > $@.log.cmp
	cmp $@.log.cmp gold/$@.log.cmp

clean:
	rm -rf $(TESTS) work *.log vsim* transcript *.vstf *.log.cmp modelsim.ini

.PHONY: $(TESTS)
