#!

# Copyright (c) 2003-2011 Stand By Soft, Ltd. All rights reserved.
#
# This software is the proprietary information of Stand By Soft, Ltd.
# Use is subject to license terms.

LOCALCLASSPATH="$CLASSPATH"
LOCALCLASSPATH="lib/RationalPlan.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/swingx.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/jdatepicker.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/jdatepicker-i18n.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/looks.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/itext.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/jxl.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/AppleJavaExtensions.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/mpxj.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/rtfparserkit.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/mail.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/activation.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/commons-lang.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/ical4j.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/backport-util-concurrent.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/commons-logging.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/poi.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/jaxb-api.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/jaxb-impl.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/jaxb-core.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/jsr173_1.0_api.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/swing-worker-1.2.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/aopalliance.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/spring-aop.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/spring-beans.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/spring-context.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/spring-core.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/spring-expression.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/spring-web.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/spring-webmvc.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/quaqua.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/jasperreports.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/jasperreports-fonts-4.0.1.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/groovy-all.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/commons-collections.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/commons-digester-2.1.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/SHEF.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/sam.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/jtidy.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/novaworx-syntax.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/jna.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/jayatana.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/dropbox-java-sdk.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/jackson-core-sdk.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/google-api-client.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/google-api-services-drive.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/google-http-client.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/google-http-client-gson.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/google-oauth-client.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/google-oauth-client-java6.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/google-oauth-client-jetty.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/grpc-context.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/opencensus-api.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/opencensus-contrib-http-util.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/guava.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/gson.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/jcommon-serializer.jar":"$LOCALCLASSPATH"
LOCALCLASSPATH="lib/resources":"$LOCALCLASSPATH"

java -Xmx512M -Xss5M -Djava.library.path=lib -cp $LOCALCLASSPATH com.sbs.jpm.Main ${1:+"$@"}
